[project]
name = "natwestsubsiccomparison"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "polars>=1.29.0",
    "tldextract>=5.3.0",
    "fastexcel (>=0.14.0,<0.15.0)",
    "xlsxwriter (>=3.2.3,<4.0.0)",
    "ruff (>=0.11.10,<0.12.0)",
]
